# Generated by Django 3.2.8 on 2021-10-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='ffile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='comment',
            name='nft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.nft'),
            preserve_default=False,
        ),
    ]
