# Generated by Django 3.2.8 on 2021-10-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211025_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='file',
        ),
    ]
