# Generated by Django 3.2.8 on 2021-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_nft_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='email',
        ),
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
