# Generated by Django 3.2.8 on 2021-10-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_nft_user'),
        ('main_app', '0005_photo'),
    ]

    operations = [
    ]
